[[plugin]]
url = "w0rp/ale"
type = "opt"

[[plugin]]
url = "alessandroyorba/sierra"
type = "opt"

[[plugin]]
url = "mattn/emmet-vim"
type = "opt"

[[plugin]]
url = "dracula/vim"
name = "dracula-vim"
type = "opt"

[[plugin]]
url = "rhysd/vim-gfm-syntax"
type = "opt"

[[plugin]]
url = "AndrewRadev/inline_edit.vim"

[[plugin]]
url = "kana/vim-altr"

[[plugin]]
url = "kana/vim-niceblock"

[[plugin]]
url = "mattn/sonictemplate-vim"

[[plugin]]
url = "mattn/webapi-vim"

[[plugin]]
url = "mhinz/vim-hugefile"

[[plugin]]
url = "sgur/vim-editorconfig"
depth = 9999

[[plugin]]
url = "sjl/gundo.vim"

[[plugin]]
url = "thinca/vim-ambicmd"

